
# AWS service name.
service: ariyan-test

custom:
  devicesTableName: ${self:service}-${self:provider.stage}-device
  devicesTableArn: # ARNs are addresses of deployed services in AWS space.
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.devicesTableName}

provider:
  name: aws
  runtime: go1.x
  stage: devices # Your development stage
  region: us-east-1
  environment:
    DEVICES_TABLE_NAME: ${self:custom.devicesTableName}
  iamRoleStatements: # Defines what other AWS services our lambda functions can access.
    - Effect: Allow # Allow access to DynamoDB tables.
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.devicesTableArn}

package:
 individually: true
 exclude:
   - ./**

functions:
  main:
    handler: main
    package:
     include:
       - ./main
    events:
      - http:
          path: /
          method: post
          cors: true
          path: /{id}
          method: get
          cors: true
     
resources:
  Resources:
    DeviceTable: # Define a new DynamoDB Table resource to store items
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.devicesTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
